Помощь друга (часть 1)
htmlacademy-javascript/1518627-kekstagram-22 pull request #6
Opened 2021-02-24 11:35 UTC by Bedmano

Добавил замену изображения при загрузке в инпут, добавил масштабирование и фильтры со слайдером

2021-02-25 22:13 UTC, at31oldfox requested changes
https://ibb.co/37kVm4D дублирует изображения при загрузке

2021-02-27 00:18 UTC, at31oldfox requested changes

2021-02-27 00:18 UTC, at31oldfox commented on js/change-scale.js
> +    if (sum < 25) {
if (sum <= 25) {

2021-03-02 17:24 UTC, at31oldfox commented on Readme.md
> +* Наставник: `Фёдор Арбузов`.
?

2021-03-02 17:25 UTC, Bedmano commented on Readme.md
> +* Наставник: `Фёдор Арбузов`.
Извини,с коммитами напутал и не заметил,что вернулось как было

2021-03-02 17:32 UTC, merged